### ISSUE TITLE
release/foxy/lgsvl_bridge/0.1.0-1 missing

### ISSUE THREAD

**Issue by shr-project** [lgsvl/ros2-lgsvl-bridge-release#1]
Did you remove this tag?

It's still referenced by older rosdistro as introduced in:
https://github.com/ros/rosdistro/commit/eaef55fb76473217a2b70fcbff20aaba046bf518

and this missing tag causes superflore to fail generating the recipes

**Comment by shr-project** [comment]
```
DEBUG:rosdistro:Skipped "github_manifest_provider()": specified tag "release/foxy/lgsvl_bridge/0.1.0-1" is not a git tag
DEBUG:rosdistro:Skip non-bitbucket url "https://github.com/lgsvl/ros2-lgsvl-bridge-release.git"
DEBUG:rosdistro:Skipped "bitbucket_manifest_provider()": Cannot handle non bitbucket url.
DEBUG:rosdistro:Skipped "git_manifest_provider()": Unable to fetch package.xml: Could not clone repository "https://github.com/lgsvl/ros2-lgsvl-bridge-release.git" at reference "release/foxy/lgsvl_bridge/0.1.0-1"
...
foxy: missing package.xml file for package "lgsvl_bridge"
```

**Comment by shr-project** [comment]
It's missing for dashing as well, causing build failures with meta-ros as well (not only when updating rosdistro cache).

ERROR: lgsvl-bridge-0.1.0-1-r0 do_fetch: Fetcher failure: Unable to find revision cef1cd71e882925c23cafefac37a586cf08ccf97 in branch release/dashing/lgsvl_bridge even from upstream

It also breaks CI on rosdistro repo:
https://github.com/shr-project/rosdistro/actions/runs/213757700
```
======================================================================
ERROR: test.test_build_caches.test_build_caches
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.5/x64/lib/python3.8/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/runner/work/rosdistro/rosdistro/test/test_build_caches.py", line 57, in test_build_caches
    raise RuntimeError('\n'.join(errors))
RuntimeError:
dashing: missing package.xml file for package "lgsvl_bridge"
eloquent: missing package.xml file for package "lgsvl_bridge"
foxy: missing package.xml file for package "lgsvl_bridge"
melodic: missing package.xml file for package "ezrassor_controller_server"
```

Can we please stop removing tags and branches?

**Comment by shr-project** [comment]
I got access to this repo and restored following tags from https://github.com/ros2-gbp-rpm/ros2-lgsvl-bridge-release fork which still had them:
```
 * [new tag]         debian/ros-dashing-lgsvl-bridge_0.1.0-1_bionic  -> debian/ros-dashing-lgsvl-bridge_0.1.0-1_bionic
 * [new tag]         debian/ros-eloquent-lgsvl-bridge_0.1.0-1_bionic -> debian/ros-eloquent-lgsvl-bridge_0.1.0-1_bionic
 * [new tag]         debian/ros-foxy-lgsvl-bridge_0.1.0-1_focal      -> debian/ros-foxy-lgsvl-bridge_0.1.0-1_focal
 * [new tag]         release/dashing/lgsvl_bridge/0.1.0-1            -> release/dashing/lgsvl_bridge/0.1.0-1
 * [new tag]         release/eloquent/lgsvl_bridge/0.1.0-1           -> release/eloquent/lgsvl_bridge/0.1.0-1
 * [new tag]         release/foxy/lgsvl_bridge/0.1.0-1               -> release/foxy/lgsvl_bridge/0.1.0-1
 * [new tag]         upstream/0.1.0                                  -> upstream/0.1.0
```

but there is another issue, that the release/*/lgsvl_bridge branches were rebased and force pushed, so the old tags no longer exist on the branch (but they do exist on the old version of the branch in the fork):
```
ros2-lgsvl-bridge-release$ git branch -a --contains release/dashing/lgsvl_bridge/0.1.0-1
  remotes/fork/debian/dashing/bionic/lgsvl_bridge
  remotes/fork/debian/dashing/lgsvl_bridge
  remotes/fork/release/dashing/lgsvl_bridge

ros2-lgsvl-bridge-release$ git branch -a --contains release/eloquent/lgsvl_bridge/0.1.0-1
  remotes/fork/debian/eloquent/bionic/lgsvl_bridge
  remotes/fork/debian/eloquent/lgsvl_bridge
  remotes/fork/release/eloquent/lgsvl_bridge
  remotes/fork/rpm/eloquent/31/lgsvl_bridge
  remotes/fork/rpm/eloquent/32/lgsvl_bridge
  remotes/fork/rpm/eloquent/7/lgsvl_bridge
  remotes/fork/rpm/eloquent/8/lgsvl_bridge
  remotes/fork/rpm/eloquent/lgsvl_bridge

ros2-lgsvl-bridge-release$ git branch -a --contains release/foxy/lgsvl_bridge/0.1.0-1
  remotes/fork/debian/foxy/focal/lgsvl_bridge
  remotes/fork/debian/foxy/lgsvl_bridge
  remotes/fork/release/foxy/lgsvl_bridge
```

I don't want to force push the current branches, because that would break the builds which do reference the new 0.1.1 and 0.1.2 tags, so I'll just restore the old version of the branch with "-before-rebase" suffix and will update meta-ros recipes to use the branches with this suffix.

```
ros2-lgsvl-bridge-release$ git log --oneline origin/release/foxy/lgsvl_bridge 
5d93a82 (tag: release/foxy/lgsvl_bridge/0.1.2-1, origin/release/foxy/lgsvl_bridge) Rebase from 'upstream' (no changes)
1c14fef (tag: upstream/0.1.2, origin/upstream) Imported upstream version '0.1.2' of 'upstream'
b5685a3 (tag: upstream/0.1.1) Imported upstream version '0.1.1' of 'upstream'
fcd519d Created orphaned branch upstream

ros2-lgsvl-bridge-release$ git log --oneline fork/release/foxy/lgsvl_bridge 
8825330 (HEAD -> release/foxy/lgsvl_bridge-before-rebase, tag: release/foxy/lgsvl_bridge/0.1.0-1, fork/release/foxy/lgsvl_bridge) Rebase from 'upstream' (no changes)
3f9745d (tag: upstream/0.1.0, fork/upstream) Imported upstream version '0.1.0' of 'upstream'
825c996 Created orphaned branch upstream

ros2-lgsvl-bridge-release$ git log --oneline origin/release/dashing/lgsvl_bridge 
ba71b8d (tag: release/dashing/lgsvl_bridge/0.1.1-1, origin/release/dashing/lgsvl_bridge) Rebase from 'upstream' (no changes)
b5685a3 (tag: upstream/0.1.1) Imported upstream version '0.1.1' of 'upstream'
fcd519d Created orphaned branch upstream

ros2-lgsvl-bridge-release$ git log --oneline fork/release/dashing/lgsvl_bridge 
cef1cd7 (tag: release/dashing/lgsvl_bridge/0.1.0-1, fork/release/dashing/lgsvl_bridge, release/dashing/lgsvl_bridge-before-rebase) Rebase from 'upstream' (no changes)
3f9745d (tag: upstream/0.1.0, fork/upstream) Imported upstream version '0.1.0' of 'upstream'
825c996 Created orphaned branch upstream

ros2-lgsvl-bridge-release$ git log --oneline origin/release/eloquent/lgsvl_bridge 
9cce450 (tag: release/eloquent/lgsvl_bridge/0.1.1-1, origin/release/eloquent/lgsvl_bridge) Rebase from 'upstream' (no changes)
b5685a3 (tag: upstream/0.1.1) Imported upstream version '0.1.1' of 'upstream'
fcd519d Created orphaned branch upstream

ros2-lgsvl-bridge-release$ git log --oneline fork/release/eloquent/lgsvl_bridge 
1cf1708 (tag: release/eloquent/lgsvl_bridge/0.1.0-1, fork/release/eloquent/lgsvl_bridge, release/eloquent/lgsvl_bridge-before-rebase) Rebase from 'upstream' (no changes)
3f9745d (tag: upstream/0.1.0, fork/upstream) Imported upstream version '0.1.0' of 'upstream'
825c996 Created orphaned branch upstream
```

**Comment by shr-project** [comment]
rosdistro CI is fixed (other than ezrassor_controller_server issue in melodic unrelated to this ticket):
https://github.com/shr-project/rosdistro/runs/1007368869
```
2020-08-20T11:23:10.6781831Z ERROR: test.test_build_caches.test_build_caches
2020-08-20T11:23:10.6783181Z ----------------------------------------------------------------------
2020-08-20T11:23:10.6784018Z Traceback (most recent call last):
2020-08-20T11:23:10.6786074Z   File "/opt/hostedtoolcache/Python/3.8.5/x64/lib/python3.8/site-packages/nose/case.py", line 198, in runTest
2020-08-20T11:23:10.6786335Z     self.test(*self.arg)
2020-08-20T11:23:10.6786821Z   File "/home/runner/work/rosdistro/rosdistro/test/test_build_caches.py", line 57, in test_build_caches
2020-08-20T11:23:10.6787288Z     raise RuntimeError('\n'.join(errors))
2020-08-20T11:23:10.6787819Z RuntimeError: melodic: missing package.xml file for package "ezrassor_controller_server"
```
and the work around in meta-ros is available as well.

Closing
